default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>        # Docker の db サービス名
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "fx_mmanager_api_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") { "fx_mmanager_api_test" } %>

production:
  <<: *default
  # 本番用はあとで環境変数で上書きする想定
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") { "fx_mmanager_api_production" } %>
  host:     <%= ENV.fetch("DB_HOST_PRODUCTION") { ENV.fetch("DB_HOST") { "db" } } %>
  username: <%= ENV.fetch("DB_USER_PRODUCTION") { ENV.fetch("DB_USER") { "postgres" } } %>
  password: <%= ENV.fetch("DB_PASSWORD_PRODUCTION") { ENV.fetch("DB_PASSWORD") { "password" } } %>
